version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: myapp_development
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5431:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rails:
    build:
      context: ./rails
    command: bash -c "tail -f log/development.log"
    volumes:
      - ./rails:/myapp
    ports:
      - 5432:5432
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  postgres_data:
